button_toggle: false
left_timer:
  text_color: white
  color: red
  music_file: /home/shaunkeys/Desktop/timer-box/benny_hill_show.wav
game_timer:
  text_color: white
  color: black
  time_secs: 300
  start_sfx: /home/shaunkeys/Desktop/timer-box/airhorn.wav
  end_sfx: /home/shaunkeys/Desktop/timer-box/airhorn.wav
right_timer:
  text_color: white
  color: blue
  music_file: /home/shaunkeys/Desktop/timer-box/baby_elephant.wav
